In [1]:
#import pandas as pd
#import numpy as np

dancers = list('abcdefghijklmnop')
test_dancers = list('abcde')

In [2]:
input_dance = open('input.txt').read().split(',')

test_dance = ['s1', 'x3/4', 'pe/b']
test_res = ['eabcd', 'eabdc', 'baedc']

In [3]:
# # massively inefficient implementation - 10 seconds per dance()
#
# class Dancers(object):
#     def __init__(self, dancers, moves):
#         self.dancers = pd.Series(dancers)
#         self.moves = moves
#         self.pc = 0
        
#     def move(self):
#         move = self.moves[self.pc]
#         if move[0] == 's':
#             dist = int(move[1:])
#             self.dancers = pd.Series(np.roll(self.dancers, dist))
#         elif move[0] == 'x':
#             a, _, b = move[1:].partition('/')
#             a, b = map(int, [a, b])
#             self.dancers[a], self.dancers[b] = self.dancers[b], self.dancers[a]
#         elif move[0] == 'p':
#             a, _, b = move[1:].partition('/')
#             a, b = self.dancers[self.dancers == a].index, self.dancers[self.dancers == b].index
#             self.dancers[a], self.dancers[b] = self.dancers[b], self.dancers[a]
#         else:
#             raise ValueError(f'no such move {move} at instruction {self.pc}')
#         self.pc += 1
#         return ''.join(self.dancers)
    
#     def dance(self):
#         while self.pc < len(self.moves):
#             self.move()
#         return ''.join(self.dancers)
    
#     def reset_pc(self):
#         self.pc = 0
    
#     def __str__(self):
#         return ''.join(self.dancers)
    
#     __repr__ = __str__

In [4]:
class Dancers(object):
    def __init__(self, dancers, moves):
        self.dancers = list(dancers)
        self.len = len(self.dancers)
        self.moves = moves
        self.pc = 0
        
    def move(self):
        move = self.moves[self.pc]
        if move[0] == 's':
            dist = int(move[1:])
            self.dancers = self.dancers[self.len-dist:] + self.dancers[:self.len-dist]
        elif move[0] == 'x':
            a, _, b = move[1:].partition('/')
            a, b = map(int, [a, b])
            self.dancers[a], self.dancers[b] = self.dancers[b], self.dancers[a]
        elif move[0] == 'p':
            a, _, b = move[1:].partition('/')
            a, b = self.dancers.index(a), self.dancers.index(b)
            self.dancers[a], self.dancers[b] = self.dancers[b], self.dancers[a]
        else:
            raise ValueError(f'no such move {move} at instruction {self.pc}')
        self.pc += 1
        return ''.join(self.dancers)
    
    def dance(self):
        while self.pc < len(self.moves):
            self.move()
        return ''.join(self.dancers)
    
    def reset_pc(self):
        self.pc = 0
    
    def __str__(self):
        return ''.join(self.dancers)
    
    __repr__ = __str__

In [5]:
d = Dancers(dancers, input_dance)

In [6]:
%%timeit -n 1 -r 1
print(f'part 1 answer: {d.dance()}')

part 1 answer: iabmedjhclofgknp
16.2 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [7]:
%%timeit -n 1 -r 1
d = Dancers(dancers, input_dance)
seen = [str(d)]
for i in range(1000000000): # only kidding...  The repeat period will be shorter than this.
    this = d.dance()
    d.reset_pc()
    #print(f'{i:3} {this}')
    if this in seen:
        period = len(seen)
        break
    seen.append(this)
print(f'part 2 answer: {seen[1000000000 % period]}')

part 2 answer: oildcmfeajhbpngk
496 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


# Timings

## Dell XPS13
```
part 1 answer: iabmedjhclofgknp
41.7 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

part 2 answer: oildcmfeajhbpngk
1.34 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

## Dell Latitude 7480
```
part 1 answer: iabmedjhclofgknp
16.2 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

part 2 answer: oildcmfeajhbpngk
496 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```